"""First migration

Revision ID: ccd632787b55
Revises: eb337ff2aa8b
Create Date: 2020-10-24 00:09:26.124182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd632787b55'
down_revision = 'eb337ff2aa8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
